name: Run JUnit tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Remove package-lock.json
        run: rm package-lock.json

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --no-watch

      - name: Publish JUnit test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results.xml
